### ISSUE TITLE
discussion

### ISSUE THREAD

**Issue by my0811** [JavaHello/java-deps.nvim#1]
可以啊，老哥，你这个弄得不错啊，我参考了你好多配置，现在有个问题是telescope查找 jar 包里面的 class，可以搜索，但是打不开

**Comment by JavaHello** [comment]
用 dev 分支试试，dev 修复了这个问题，貌似是  neovim 0.9.1 版本有什么修改导致的。

**Comment by JavaHello** [comment]
> 可以啊，老哥，你这个弄得不错啊，我参考了你好多配置，现在有个问题是telescope查找 jar 包里面的 class，可以搜索，但是打不开

https://github.com/JavaHello/nvim/tree/dev 用 dev 分支试试
